/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import infra.Banco;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Pais;

/**
 *
 * @author paulo
 */
public class Janela extends javax.swing.JFrame {

    private Banco bd;
    
    public Janela() {
        this.bd = new Banco();
        initComponents();
    }
/**
     * Creates new form Janela
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeClienteLb = new javax.swing.JLabel();
        idadeLb = new javax.swing.JLabel();
        telefoneLb = new javax.swing.JLabel();
        paisClienteLb = new javax.swing.JLabel();
        nomeClienteTx = new javax.swing.JTextField();
        idadeTx = new javax.swing.JTextField();
        telTx = new javax.swing.JTextField();
        paisClienteTx = new javax.swing.JTextField();
        cadastrarClienteBtn = new javax.swing.JButton();
        nomePaisTx = new javax.swing.JTextField();
        siglaTx = new javax.swing.JTextField();
        tamanhoTelTx = new javax.swing.JTextField();
        nomePaisLb = new javax.swing.JLabel();
        siglaLb = new javax.swing.JLabel();
        tamanhoTelLb = new javax.swing.JLabel();
        cadastrarPaisBtn = new javax.swing.JButton();
        clienteLb = new javax.swing.JLabel();
        paisLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeClienteLb.setText("Nome");

        idadeLb.setText("Idade");

        telefoneLb.setText("Telefone");

        paisClienteLb.setText("País");

        cadastrarClienteBtn.setText("Cadastrar Cliente");
        cadastrarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteBtnActionPerformed(evt);
            }
        });

        nomePaisTx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomePaisLb.setText("Nome");

        siglaLb.setText("Sigla");

        tamanhoTelLb.setText("Tam Telefone");

        cadastrarPaisBtn.setText("Cadastrar País");
        cadastrarPaisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPaisBtnActionPerformed(evt);
            }
        });

        clienteLb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clienteLb.setText("CLIENTE");

        paisLb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paisLb.setText("PAÍS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(clienteLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paisLb)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisClienteLb)
                                    .addComponent(telefoneLb))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telTx)
                                    .addComponent(paisClienteTx, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idadeLb)
                                    .addComponent(nomeClienteLb))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeClienteTx)
                                    .addComponent(idadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamanhoTelLb)
                            .addComponent(siglaLb)
                            .addComponent(nomePaisLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(cadastrarClienteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarPaisBtn)
                    .addComponent(siglaTx, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePaisTx, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamanhoTelTx, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLb)
                    .addComponent(paisLb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomePaisTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePaisLb))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siglaTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siglaLb))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tamanhoTelTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tamanhoTelLb)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeClienteLb)
                            .addComponent(nomeClienteTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idadeLb)
                            .addComponent(idadeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefoneLb)
                            .addComponent(telTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paisClienteLb)
                            .addComponent(paisClienteTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarPaisBtn)
                    .addComponent(cadastrarClienteBtn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteBtnActionPerformed
        try {
            Cliente c = new Cliente(nomeClienteTx.getText(),
                                    Integer.parseInt(idadeTx.getText()),
                                    telTx.getText());
            bd.addCliente(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarClienteBtnActionPerformed

    private void cadastrarPaisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPaisBtnActionPerformed
        try {
            Pais p = new Pais(nomePaisTx.getText(),
                              siglaTx.getText(),
                              Integer.parseInt(tamanhoTelTx.getText()));
            bd.addPais(p);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cadastrarPaisBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarClienteBtn;
    private javax.swing.JButton cadastrarPaisBtn;
    private javax.swing.JLabel clienteLb;
    private javax.swing.JLabel idadeLb;
    private javax.swing.JTextField idadeTx;
    private javax.swing.JLabel nomeClienteLb;
    private javax.swing.JTextField nomeClienteTx;
    private javax.swing.JLabel nomePaisLb;
    private javax.swing.JTextField nomePaisTx;
    private javax.swing.JLabel paisClienteLb;
    private javax.swing.JTextField paisClienteTx;
    private javax.swing.JLabel paisLb;
    private javax.swing.JLabel siglaLb;
    private javax.swing.JTextField siglaTx;
    private javax.swing.JLabel tamanhoTelLb;
    private javax.swing.JTextField tamanhoTelTx;
    private javax.swing.JTextField telTx;
    private javax.swing.JLabel telefoneLb;
    // End of variables declaration//GEN-END:variables
}
